POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "miteux",
    "name": "Miteux LeChat",
    "password": "iambread"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mbrillante",
    "name": "Martina Brillante",
    "password": "coffeeforlife"
}