POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Hot for Food",
    "author": "Lauren Toyota",
    "url": "https://www.hotforfoodblog.com/"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Nutriciously",
    "author": "Alena",
    "url": "https://nutriciously.com/"
}