POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Smart Bitches, Trashy Books",
    "author": "various",
    "url": "https://smartbitchestrashybooks.com/"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Vegan Richa",
    "author": "Richa",
    "url": "https://www.veganricha.com/"
}