DELETE http://localhost:3003/api/blogs/6447c8e5b2249b07e2392184
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Heart of a Beanie",
    "author": "Abby",
    "url": "https://heartofabaker.com/"
}
//Beanie ^
###
DELETE http://localhost:3003/api/blogs/642c017c205faa50b69d5d6c
Content-Type: application/json
Authorization: Bearer 

{
    "title": "Heart of a Bake",
    "author": "Abby",
    "url": "https://heartofabaker.com/"
}
//Miteux ^
