POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "beaniebaby",
    "password": "meow"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "miteux",
    "password": "iambread"
}
